# Generated by Django 6.1 on 2026-08-22 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Half-day', 'Half-day'), ('On leave', 'On leave'), ('Late', 'Late'), ('Off', 'Off'), ('Absent', 'Absent'), ('Remote', 'Remote')], default='Present', max_length=30)),
                ('check_in', models.CharField(blank=True, default='—', max_length=30)),
                ('check_out', models.CharField(blank=True, default='—', max_length=30)),
                ('work_hours', models.CharField(blank=True, default='—', max_length=30)),
                ('location', models.CharField(default='New Delhi', max_length=100)),
                ('tone', models.CharField(default='protected', max_length=30)),
                ('issue', models.CharField(blank=True, default='', max_length=255)),
                ('is_exception', models.BooleanField(default=False)),
                ('exception_time', models.CharField(blank=True, default='', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
