<template>
  <section>
    <header class="page-title-row"><div><p class="eyebrow">Attendance intelligence</p><h1>Every hour, accounted for.</h1><p>Spot exceptions early without turning presence into surveillance.</p></div><div class="header-actions"><button class="secondary-button" type="button" @click="$emit('toast','Attendance CSV prepared')"><Icon name="download" /> Export</button><button class="primary-button" type="button" @click="$emit('toast','Attendance marked for today')"><Icon name="check" /> Mark attendance</button></div></header>
    <div class="summary-grid four"><article class="summary-card"><span class="metric-icon"><Icon name="check" /></span><div><small>Present today</small><strong>98</strong><em>81.7% of team</em></div></article><article class="summary-card"><span class="metric-icon"><Icon name="clock" /></span><div><small>Average check-in</small><strong>09:06</strong><em>4 min earlier</em></div></article><article class="summary-card"><span class="metric-icon warning"><Icon name="spark" /></span><div><small>Exceptions</small><strong>6</strong><em>2 need action</em></div></article><article class="summary-card"><span class="metric-icon"><Icon name="user" /></span><div><small>Remote today</small><strong>10</strong><em>8.3% of team</em></div></article></div>
    <div class="content-grid attendance-content">
      <article class="surface weekly-panel"><header class="section-heading"><div><span class="section-kicker">18–24 August 2026</span><h2>Weekly attendance</h2></div><div class="week-control"><button type="button">‹</button><strong>This week</strong><button type="button">›</button></div></header><div class="attendance-chart"><div v-for="bar in days" :key="bar.day" class="attendance-day"><div class="chart-track"><span :style="{height: bar.value + '%'}" :class="bar.tone"></span></div><strong>{{ bar.value }}%</strong><small>{{ bar.day }}</small></div></div><div class="chart-legend"><span><i class="teal"></i> Present</span><span><i class="amber"></i> Half day</span><span><i class="coral"></i> Exception</span></div></article>
      <article class="surface exceptions-panel"><header class="section-heading"><div><span class="section-kicker">Requires review</span><h2>Attendance exceptions</h2></div><span class="status pending">2 urgent</span></header><button v-for="item in exceptions" :key="item.name" class="exception-item" type="button" @click="$emit('toast', `${item.name}'s attendance opened`)"><span class="avatar" :class="item.color">{{ item.initials }}</span><span><strong>{{ item.name }}</strong><small>{{ item.issue }}</small></span><time>{{ item.time }}</time><Icon name="chevron" /></button><button class="text-button wide" type="button">View all exceptions <Icon name="arrow" /></button></article>
    </div>
    <article class="surface table-surface"><header class="section-heading table-heading"><div><span class="section-kicker">Live today</span><h2>Team attendance</h2></div><label class="search-box"><Icon name="search" /><input v-model="search" placeholder="Search employee" /></label></header><div class="attendance-table table-scroll"><div class="table-row table-head"><span>Employee</span><span>Status</span><span>Check-in</span><span>Check-out</span><span>Work hours</span><span>Location</span></div><div v-for="item in filteredRows" :key="item.name" class="table-row"><span class="employee-cell"><span class="avatar" :class="item.color">{{ item.initials }}</span><strong>{{ item.name }}</strong></span><span><span class="status" :class="item.tone">{{ item.status }}</span></span><span>{{ item.in }}</span><span>{{ item.out }}</span><span>{{ item.hours }}</span><span>{{ item.location }}</span></div></div></article>
  </section>
</template>
<script setup>
import { computed, ref } from "vue"
import Icon from "./Icon.vue"
defineEmits(["toast"])
const search = ref("")
const days = [{day:"Mon",value:94,tone:"good"},{day:"Tue",value:97,tone:"good"},{day:"Wed",value:88,tone:"warn"},{day:"Thu",value:96,tone:"good"},{day:"Fri",value:98,tone:"good"},{day:"Sat",value:72,tone:"low"},{day:"Sun",value:40,tone:"low"}]
const exceptions=[{name:"Rohit Sharma",initials:"RS",issue:"Missing check-in · 21 Aug",time:"1d",color:"coral"},{name:"Vikram Singh",initials:"VS",issue:"Late arrival · 42 minutes",time:"2h",color:"amber"},{name:"Maya Patel",initials:"MP",issue:"Location mismatch",time:"3h",color:"violet"}]
const rows=[{name:"Neha Sharma",initials:"NS",status:"Present",tone:"protected",in:"09:04",out:"—",hours:"6h 42m",location:"New Delhi",color:"teal"},{name:"Priya Desai",initials:"PD",status:"Present",tone:"protected",in:"08:58",out:"—",hours:"6h 48m",location:"Bengaluru",color:"violet"},{name:"Aisha Khan",initials:"AK",status:"On leave",tone:"pending",in:"—",out:"—",hours:"—",location:"Mumbai",color:"blue"},{name:"Vikram Singh",initials:"VS",status:"Late",tone:"risk",in:"09:42",out:"—",hours:"6h 04m",location:"New Delhi",color:"amber"}]
const filteredRows=computed(()=>rows.filter(item=>item.name.toLowerCase().includes(search.value.toLowerCase())))
</script>
