<template>
  <section>
    <header class="page-title-row"><div><p class="eyebrow">Payroll readiness</p><h1>Close payroll without the scramble.</h1><p>Catch attendance, leave and compensation issues before they become payroll errors.</p></div><div class="header-actions"><button class="secondary-button" type="button" @click="$emit('toast','Payroll report downloaded')"><Icon name="download" /> Report</button><button class="primary-button" type="button" @click="runPayroll"><Icon name="rupee" /> {{ running ? 'Checking…' : 'Run payroll check' }}</button></div></header>
    <div class="payroll-hero surface"><div class="readiness-ring"><span><strong>{{ running ? '100' : '90' }}</strong><small>% ready</small></span></div><div><span class="section-kicker">August 2026 payroll</span><h2>{{ running ? 'Payroll is ready to close' : 'Almost ready. Twelve checks remain.' }}</h2><p>{{ running ? 'All 120 employee records passed validation.' : 'Resolve attendance and bank-detail exceptions before 28 August.' }}</p><div class="payroll-tags"><span><Icon name="check" /> 108 cleared</span><span class="warn"><Icon name="clock" /> {{ running ? 0 : 12 }} to review</span><span><Icon name="calendar" /> 6 days left</span></div></div><button class="primary-button dark" type="button" @click="runPayroll">{{ running ? 'Close payroll' : 'Review 12 checks' }} <Icon name="arrow" /></button></div>
    <div class="summary-grid four"><article class="summary-card"><span class="metric-icon"><Icon name="rupee" /></span><div><small>Gross payroll</small><strong>₹84.6L</strong><em>+3.2% MoM</em></div></article><article class="summary-card"><span class="metric-icon"><Icon name="users" /></span><div><small>Employees</small><strong>120</strong><em>All included</em></div></article><article class="summary-card"><span class="metric-icon"><Icon name="calendar" /></span><div><small>Pay date</small><strong>31 Aug</strong><em>On schedule</em></div></article><article class="summary-card"><span class="metric-icon warning"><Icon name="spark" /></span><div><small>Exceptions</small><strong>{{ running ? 0 : 12 }}</strong><em>{{ running ? 'Resolved' : 'Need review' }}</em></div></article></div>
    <div class="content-grid payroll-grid"><article class="surface"><header class="section-heading"><div><span class="section-kicker">Pre-flight checks</span><h2>Payroll checklist</h2></div><span class="status protected">{{ running ? 'Complete' : '90%' }}</span></header><button v-for="check in checks" :key="check.label" type="button" class="payroll-check"><span class="metric-icon" :class="check.tone"><Icon :name="check.icon" /></span><span><strong>{{check.label}}</strong><small>{{running ? 'No issues found' : check.detail}}</small></span><span class="status" :class="running ? 'protected' : check.statusTone">{{running ? 'Clear' : check.status}}</span><Icon name="chevron" /></button></article><article class="surface cost-card"><header class="section-heading"><div><span class="section-kicker">Monthly trend</span><h2>Payroll cost</h2></div><span class="status protected">Stable</span></header><div class="cost-chart"><div v-for="month in months" :key="month.name"><span :style="{height:month.value+'%'}"></span><strong>₹{{month.amount}}L</strong><small>{{month.name}}</small></div></div><div class="forecast"><span><small>September forecast</small><strong>₹86.1L</strong></span><span><small>Expected change</small><strong>+1.8%</strong></span></div></article></div>
  </section>
</template>
<script setup>
import { ref } from "vue"
import Icon from "./Icon.vue"
const emit=defineEmits(["toast"])
const running=ref(false)
const checks=[{label:"Attendance inputs",detail:"2 missing check-ins",status:"2 issues",statusTone:"risk",icon:"clock",tone:"warning"},{label:"Leave adjustments",detail:"3 requests pending",status:"3 pending",statusTone:"pending",icon:"leave",tone:"warning"},{label:"Bank details",detail:"7 profiles incomplete",status:"7 issues",statusTone:"risk",icon:"building",tone:"warning"},{label:"Compensation changes",detail:"All approved",status:"Clear",statusTone:"protected",icon:"rupee",tone:""}]
const months=[{name:"Mar",value:63,amount:"77.2"},{name:"Apr",value:68,amount:"78.9"},{name:"May",value:72,amount:"80.4"},{name:"Jun",value:79,amount:"82.1"},{name:"Jul",value:86,amount:"83.5"},{name:"Aug",value:92,amount:"84.6"}]
function runPayroll(){running.value=true;emit("toast","Payroll validation completed — all checks are clear")}
</script>
