<template>
  <section>
    <header class="page-title-row"><div><p class="eyebrow">Roster planning</p><h1>Coverage you can see and trust.</h1><p>Build the week around skills, workload and the people who make it work.</p></div><div class="header-actions"><button class="secondary-button" type="button"><Icon name="download" /> Export</button><button class="primary-button" type="button" @click="publish"><Icon name="check" /> {{ published ? 'Published' : 'Publish roster' }}</button></div></header>
    <div class="roster-banner surface"><div><span class="section-kicker">18–24 August 2026</span><h2>{{ published ? 'Roster published to the team' : 'Next week is 98% covered' }}</h2><p>{{ published ? 'Everyone has been notified of their assigned shifts.' : 'One evening shift needs a support specialist before publishing.' }}</p></div><div class="coverage-meter"><span :style="{width: published ? '100%' : '98%'}"></span></div><strong>{{published ? '100%' : '98%'}}</strong></div>
    <article class="surface roster-surface"><header class="section-heading table-heading"><div><span class="section-kicker">Weekly schedule</span><h2>Team roster</h2></div><div class="shift-legend"><span><i class="morning"></i> Morning</span><span><i class="evening"></i> Evening</span><span><i class="night"></i> Night</span><span><i class="leave"></i> Leave</span><span><i class="off"></i> Off</span></div></header><div class="roster-table table-scroll"><div class="roster-row roster-head"><span>Employee</span><span v-for="day in days" :key="day.name"><b>{{day.name}}</b><small>{{day.date}} Aug</small></span></div><div v-for="person in people" :key="person.name" class="roster-row"><span class="employee-cell"><span class="avatar" :class="person.color">{{person.initials}}</span><span><strong>{{person.name}}</strong><small>{{person.role}}</small></span></span><button v-for="(shift,index) in person.shifts" :key="index" type="button" class="shift-cell" :class="shift.type" @click="cycleShift(person,index)"><b>{{shift.code}}</b><small>{{shift.label}}</small></button></div></div></article>
    <div class="content-grid roster-bottom"><article class="surface"><header class="section-heading"><div><span class="section-kicker">Skill coverage</span><h2>Coverage by team</h2></div></header><div v-for="team in teams" :key="team.name" class="team-coverage"><span><strong>{{team.name}}</strong><small>{{team.detail}}</small></span><div class="progress"><span :style="{width:team.value+'%'}" :class="team.value<90?'warn':'good'"></span></div><b>{{team.value}}%</b></div></article><article class="surface"><header class="section-heading"><div><span class="section-kicker">Watch list</span><h2>Potential gaps</h2></div></header><div class="gap-item"><span class="metric-icon warning"><Icon name="spark" /></span><span><strong>Saturday evening · Support</strong><small>1 experienced specialist still needed</small></span><button class="text-button" type="button" @click="$emit('toast','Best-fit employees highlighted')">Find cover</button></div><div class="gap-item safe"><span class="metric-icon"><Icon name="shield" /></span><span><strong>All critical skills protected</strong><small>No single-point-of-failure shifts</small></span></div></article></div>
  </section>
</template>
<script setup>
import { ref } from "vue"
import Icon from "./Icon.vue"
const emit=defineEmits(["toast"])
const published=ref(false)
const days=[{name:"Mon",date:18},{name:"Tue",date:19},{name:"Wed",date:20},{name:"Thu",date:21},{name:"Fri",date:22},{name:"Sat",date:23},{name:"Sun",date:24}]
const base={M:{code:"M",label:"Morning",type:"morning"},E:{code:"E",label:"Evening",type:"evening"},N:{code:"N",label:"Night",type:"night"},L:{code:"L",label:"Leave",type:"leave"},W:{code:"W",label:"Weekly off",type:"off"}}
const people=ref([{name:"Neha Sharma",initials:"NS",role:"Engineering",color:"teal",shifts:"MMEMMWW".split("").map(k=>({...base[k]}))},{name:"Rohit Sharma",initials:"RS",role:"Support",color:"coral",shifts:"EEMMENW".split("").map(k=>({...base[k]}))},{name:"Aisha Khan",initials:"AK",role:"Product",color:"blue",shifts:"MLLMEWW".split("").map(k=>({...base[k]}))},{name:"Vikram Singh",initials:"VS",role:"Operations",color:"amber",shifts:"NNEMMWW".split("").map(k=>({...base[k]}))},{name:"Priya Desai",initials:"PD",role:"Finance",color:"violet",shifts:"MMELEM W".replace(/ /g,"").split("").map(k=>({...base[k]}))}])
const teams=[{name:"Engineering",detail:"28 / 29 required",value:97},{name:"Customer Success",detail:"17 / 19 required",value:89},{name:"Operations",detail:"22 / 22 required",value:100},{name:"Finance",detail:"12 / 12 required",value:100}]
const cycle=[base.M,base.E,base.N,base.L,base.W]
function cycleShift(person,index){const current=cycle.findIndex(item=>item.code===person.shifts[index].code);person.shifts[index]={...cycle[(current+1)%cycle.length]};emit("toast",`${person.name}'s shift updated`)}
function publish(){published.value=true;emit("toast","Roster published and team notified")}
</script>
