services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD:-123}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/docker/init.sh
    environment:
      - SHELL=/bin/bash
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-123}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    volumes:
      - ..:/workspace/code
      - .:/workspace/docker
      - bench-data:/home/frappe/bench-data
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - postgres
      - redis

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "8080:8080"
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
    depends_on:
      - frappe

volumes:
  postgres-data:
  bench-data:
