# Generated by Django 6.1 on 2026-08-22 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='August', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('is_closed', models.BooleanField(default=False)),
                ('gross_amount_lakhs', models.DecimalField(decimal_places=1, default=84.6, max_digits=6)),
                ('readiness_percent', models.IntegerField(default=90)),
                ('exceptions_count', models.IntegerField(default=12)),
                ('pay_date', models.CharField(default='31 Aug 2026', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.IntegerField(default=60000)),
                ('hra', models.IntegerField(default=18000)),
                ('special', models.IntegerField(default=12000)),
                ('other', models.IntegerField(default=5000)),
                ('deductions', models.IntegerField(default=12680)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
