# Generated by Django 6.1 on 2026-08-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_probation',
            field=models.BooleanField(default=False),
        ),
    ]
