# Generated by Django 6.1 on 2026-08-22 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('coverage_percent', models.IntegerField(default=98)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('code', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('N', 'Night'), ('L', 'Leave'), ('W', 'Weekly off')], default='M', max_length=5)),
                ('label', models.CharField(default='Morning', max_length=50)),
                ('shift_type', models.CharField(default='morning', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee__first_name', 'date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
